language: ruby

rvm:
  - 2.4.1

services:
  - postgresql

before_script:
  - psql -c 'create database imbd_group_project_test;' -U postgres

script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec spec/